### ISSUE TITLE
Copy project issues to Kanban board

### ISSUE THREAD

**Issue by aimalamiri** [aimalamiri/Space-Travelers#21]
## Copied all of the issues to the project and to the kanban board
> We are 2 persons in our team

Project link: https://github.com/aimalamiri/Space-Travelers/projects/1

**Comment by Kingstalux** [comment]
Hi @aimalamiri and @Theophileaseh, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966](https://user-images.githubusercontent.com/85113567/173337580-d3e8b09a-ffde-45c4-853c-efc0da0aa61b.gif)



## Required Changes ♻️
- [ ] Kindly make sure you have the same cards as the original [Kanban baord](https://github.com/microverseinc/curriculum-react-redux/projects/1) because right now your cards are from a completely different project. Kindly rectify that 👍 
- [ ] For groups of 2, the total number of cards should be 17. Kindly make sure you only have the relevant cards present 💯 
- [ ] Also, all cards should be assigned to a partner and the distribution should be fairly done so that all partners will have cards from all the categories 😄 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
### **Hi @aimalamiri,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
